services:
  mysql:
    image: "mysql:8"
    networks:
      mysql_network:
        aliases:
          - mysql-docker
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=metakgp_wiki_db
      - MYSQL_USER=metakgp_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  nginx:
    build: "./nginx"
    networks:
      main_network:
    volumes:
      - mediawiki-volume:/srv/mediawiki
    ports:
      - "${SERVER_PORT:-8080}:80"

  php:
    build: "./php"
    networks:
      mysql_network:
      main_network:
        aliases:
          - php-docker
    volumes:
      - mediawiki-volume:/srv/mediawiki
    environment:
      - MAILGUN_PASSWORD=$MAILGUN_PASSWORD
      - RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
      - WG_SECRET_KEY=$WG_SECRET_KEY
      - SITE_UPGRADE_KEY=$SITE_UPGRADE_KEY
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - SERVER_NAME=$SERVER_NAME
      - SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL

  mediawiki:
    build: "./mediawiki"
    volumes:
      - mediawiki-volume:/srv/mediawiki

networks:
  main_network:
    external: true
    name: metakgp-wiki_main_network
  mysql_network:

volumes:
  mediawiki-volume:
  db-volume:
  static-volume: