include:
  - docker-compose.yml

services:
  jobs:
    image: metakgporg/wiki-jobs
    container_name: wiki-jobs
    build: "./jobs"
    restart: always
    networks:
      mysql-network:
    environment:
      - BATMAN_BOT_PASSWORD=$BATMAN_BOT_PASSWORD
      - GOOGLE_ANALYTICS_SERVICE_KEY=$GOOGLE_ANALYTICS_SERVICE_KEY
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - DROPBOX_APP_KEY=$DROPBOX_APP_KEY
      - DROPBOX_APP_SECRET=$DROPBOX_APP_SECRET
      - DROPBOX_ACCESS_TOKEN=$DROPBOX_ACCESS_TOKEN
      - DROPBOX_REFRESH_TOKEN=$DROPBOX_REFRESH_TOKEN
      - SLACK_INCIDENTS_WH_URL=$SLACK_INCIDENTS_WH_URL
    volumes:
      - mediawiki-volume:/srv/mediawiki
      - db-volume:/var/lib/mysql
      - static-volume:/srv/static
