version: "2.1"

services:
  mysql:
    image: "mysql:5.7"
    networks:
      mysql_network:
        aliases:
          - mysql-docker
      data_network:
        aliases:
          - mysql-docker
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=metakgp_wiki_db
      - MYSQL_USER=metakgp_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  nginx:
    build: "./nginx"
    networks:
      main_network:
  php:
    build: "./php"
    networks:
      data_network:
      main_network:
        aliases:
          - php-docker
    environment:
      - MAILGUN_PASSWORD=$MAILGUN_PASSWORD
      - RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
      - WG_SECRET_KEY=$WG_SECRET_KEY
      - SITE_UPGRADE_KEY=$SITE_UPGRADE_KEY
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - SERVER_NAME=$SERVER_NAME
      - SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
      - NEWRELIC_LICENSE=$NEWRELIC_LICENSE
  mediawiki:
    build: "./mediawiki"

networks:
  main_network:
    external: true
    name: metakgp-wiki_main_network
  mysql_network:
  data_network:
