services:
  mysql:
    image: "mysql:8"
    networks:
      mysql-network:
        aliases:
          - mysql-docker
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=metakgp_wiki_db
      - MYSQL_USER=metakgp_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  mediawiki:
    build: "./mediawiki"
    networks:
      mysql-network:
      mediawiki-network:
        aliases:
          - mediawiki-docker
    volumes:
      - mediawiki-volume:/srv/mediawiki
      - static-volume:/srv/static
    environment:
      - MAILGUN_PASSWORD=$MAILGUN_PASSWORD
      - WG_SECRET_KEY=$WG_SECRET_KEY
      - SITE_UPGRADE_KEY=$SITE_UPGRADE_KEY
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - SERVER_NAME=$SERVER_NAME
      - SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL

  nginx:
    build: "./nginx"
    networks:
      metaploy-network:
        aliases:
          - metawiki
      mediawiki-network:
    volumes:
      - mediawiki-volume:/srv/mediawiki
      - static-volume:/srv/static
      - nginx-config-volume:/etc/nginx/sites-enabled

networks:
  mysql-network:
  mediawiki-network:
  metaploy-network:
    external: true
    name: metaploy-network

volumes:
  mediawiki-volume:
  db-volume:
  static-volume:
  nginx-config-volume:
    external: true
    name: metaploy-nginx-config-volume