# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: cd1caa72b02b64185d9394fff1d0d122996f5ad0 $
Configuration parameters:
  url = https://wiki.metakgp.org
  name = metakgp
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'metakgp'
        self.langs = {
            'en': 'wiki.metakgp.org',
        }

    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'en': u'1.28.2',
        }[code]

    def protocol(self, code):
        return {
            'en': u'https',
        }[code]
